package com.codeturret.service;

import com.codeturret.model.Finding;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Batches findings by file, generates AI patches, and returns a map of
 * filePath -> patchedContent.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class AutoFixService {

    private final LlmService llmService;

    public record FileFixResult(String filePath, String patchedContent, int findingsFixed, String error) {}

    /**
     * Generate fixes for all fixable findings in the scan.
     *
     * @param findingsPerFile Map of filePath -> list of findings for that file
     * @param fileContents    Map of filePath -> current file content
     * @return list of fix results (one per file)
     */
    public List<FileFixResult> generateFixes(
        Map<String, List<Finding>> findingsPerFile,
        Map<String, String> fileContents
    ) {
        List<FileFixResult> results = new ArrayList<>();

        for (Map.Entry<String, List<Finding>> entry : findingsPerFile.entrySet()) {
            String filePath = entry.getKey();
            List<Finding> findings = entry.getValue();
            String content = fileContents.get(filePath);

            if (content == null || content.isBlank()) {
                results.add(new FileFixResult(filePath, null, 0, "File content unavailable"));
                continue;
            }

            try {
                List<LlmService.FindingRaw> raws = findings.stream()
                    .map(f -> new LlmService.FindingRaw(
                        f.getLineNumber(), f.getSeverity().name(), f.getVulnType(),
                        f.getDescription(), f.getFixSuggestion(), f.getConfidence(),
                        f.getCodeSnippet(), null, null
                    ))
                    .toList();

                String patched = llmService.generateFix(content, filePath, raws);
                if (patched != null && !patched.isBlank()) {
                    results.add(new FileFixResult(filePath, patched, findings.size(), null));
                } else {
                    results.add(new FileFixResult(filePath, null, 0, "AI returned empty patch"));
                }
            } catch (Exception e) {
                log.warn("Fix generation failed for {}: {}", filePath, e.getMessage());
                results.add(new FileFixResult(filePath, null, 0, e.getMessage()));
            }
        }

        return results;
    }

    /**
     * Group a list of findings by their filePath.
     */
    public Map<String, List<Finding>> groupByFile(List<Finding> findings) {
        return findings.stream().collect(Collectors.groupingBy(Finding::getFilePath));
    }

    /**
     * Build the PR body listing all findings that were fixed.
     */
    public String buildPrBody(List<FileFixResult> results, String scanId) {
        StringBuilder sb = new StringBuilder();
        sb.append("## CodeTurret Security Fixes\n\n");
        sb.append("Automatically generated fixes for scan `").append(scanId).append("`.\n\n");

        int totalFixed = results.stream().mapToInt(FileFixResult::findingsFixed).sum();
        int filesFixed = (int) results.stream().filter(r -> r.patchedContent() != null).count();

        sb.append("**").append(totalFixed).append("** vulnerabilities fixed across **")
          .append(filesFixed).append("** files.\n\n");

        sb.append("### Fixed Files\n\n");
        for (FileFixResult r : results) {
            if (r.patchedContent() != null) {
                sb.append("- `").append(r.filePath()).append("` — ")
                  .append(r.findingsFixed()).append(" finding(s) fixed\n");
            }
        }

        int failed = (int) results.stream().filter(r -> r.patchedContent() == null).count();
        if (failed > 0) {
            sb.append("\n### Skipped Files\n\n");
            for (FileFixResult r : results) {
                if (r.patchedContent() == null) {
                    sb.append("- `").append(r.filePath()).append("` — ").append(r.error()).append("\n");
                }
            }
        }

        sb.append("\n---\n*Generated by [CodeTurret](https://github.com/codeturret)*");
        return sb.toString();
    }
}
