-- ============================================================
-- CodeBouncer: Database, Schema & Warehouse Setup
-- ============================================================

CREATE DATABASE IF NOT EXISTS CODEBOUNCER;

CREATE SCHEMA IF NOT EXISTS CODEBOUNCER.CORE;
CREATE SCHEMA IF NOT EXISTS CODEBOUNCER.INTEGRATIONS;

CREATE WAREHOUSE IF NOT EXISTS CODEBOUNCER_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE CODEBOUNCER;
USE SCHEMA CORE;
USE WAREHOUSE CODEBOUNCER_WH;
