-- ============================================================
-- CodeBouncer: Tables & Views
-- ============================================================

USE DATABASE CODEBOUNCER;
USE SCHEMA CORE;

-- Monitored repositories
CREATE TABLE IF NOT EXISTS REPOSITORY_CONFIG (
    REPO_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    REPO_NAME       VARCHAR(255) NOT NULL,
    REPO_URL        VARCHAR(1024) NOT NULL,
    GIT_REPO_NAME   VARCHAR(255) NOT NULL,          -- Snowflake git repository object name
    DEFAULT_BRANCH  VARCHAR(128) DEFAULT 'main',
    FILE_EXTENSIONS ARRAY DEFAULT ARRAY_CONSTRUCT('.py', '.js', '.ts'),
    IS_ACTIVE       BOOLEAN DEFAULT TRUE,
    DEEP_SCAN       BOOLEAN DEFAULT FALSE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- One row per scan execution
CREATE TABLE IF NOT EXISTS SCAN_HISTORY (
    SCAN_ID             VARCHAR(36) PRIMARY KEY,
    REPO_ID             NUMBER REFERENCES REPOSITORY_CONFIG(REPO_ID),
    BRANCH              VARCHAR(128),
    COMMIT_HASH         VARCHAR(40),
    PREV_COMMIT_HASH    VARCHAR(40),
    STATUS              VARCHAR(20) DEFAULT 'PENDING',
    FILES_SCANNED       NUMBER DEFAULT 0,
    FINDINGS_COUNT      NUMBER DEFAULT 0,
    SCAN_TYPE           VARCHAR(20) DEFAULT 'INCREMENTAL',
    STARTED_AT          TIMESTAMP_NTZ,
    COMPLETED_AT        TIMESTAMP_NTZ,
    ERROR_MESSAGE       VARCHAR(4096)
);

-- Individual vulnerability findings
CREATE TABLE IF NOT EXISTS SCAN_RESULTS (
    FINDING_ID      VARCHAR(36) PRIMARY KEY,
    SCAN_ID         VARCHAR(36) REFERENCES SCAN_HISTORY(SCAN_ID),
    REPO_ID         NUMBER REFERENCES REPOSITORY_CONFIG(REPO_ID),
    FILE_PATH       VARCHAR(1024) NOT NULL,
    LINE_NUMBER     NUMBER,
    SEVERITY        VARCHAR(10) NOT NULL,
    VULN_TYPE       VARCHAR(128) NOT NULL,
    DESCRIPTION     VARCHAR(4096),
    FIX_SUGGESTION  VARCHAR(4096),
    CODE_SNIPPET    VARCHAR(4096),
    MODEL_USED      VARCHAR(64),
    CONFIDENCE      FLOAT,
    RAW_RESPONSE    VARIANT,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Aggregated view for the dashboard heatmap
CREATE OR REPLACE VIEW SCAN_HEATMAP AS
SELECT
    sr.FILE_PATH,
    sr.SEVERITY,
    COUNT(*)        AS FINDING_COUNT,
    sh.SCAN_ID,
    sh.COMMIT_HASH,
    rc.REPO_NAME
FROM SCAN_RESULTS sr
JOIN SCAN_HISTORY sh ON sr.SCAN_ID = sh.SCAN_ID
JOIN REPOSITORY_CONFIG rc ON sr.REPO_ID = rc.REPO_ID
GROUP BY sr.FILE_PATH, sr.SEVERITY, sh.SCAN_ID, sh.COMMIT_HASH, rc.REPO_NAME;
